### ISSUE TITLE
Error in Face Tracking

### ISSUE THREAD

**Issue by SpoonCA** [leigh-johnson/rpi-deep-pantilt#38]
* rpi-deep-pantilt version: 1.2.0
* Python version: 3.3.3
* TensorFlow version: 2.2.0
* Operating System: buster

### Description

I followed the instruction on readme and issue #37, and successful ran the general detect command. However when using "detect face" command, the camera overlay would appear but the detection would not run. Failed log attached below.

### What I Did

```
(.venv2) pi@raspberrypi:~/pantilt $ rpi-deep-pantilt detect face
^[[6~^[[6~WARNING:root:Detecting labels: ('face',)
^[[6~Traceback (most recent call last):
  File "/home/pi/pantilt/.venv2/bin/rpi-deep-pantilt", line 10, in <module>
    sys.exit(main())
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/rpi_deep_pantilt/cli.py", line 172, in main
    cli()
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/rpi_deep_pantilt/cli.py", line 96, in detect
    run_stationary_detect(labels, model_cls, rotation)
  File "/home/pi/pantilt/.venv2/lib/python3.7/site-packages/rpi_deep_pantilt/detect/camera.py", line 99, in run_stationary_detect
    filtered_prediction = model.filter_tracked(
AttributeError: 'FaceSSD_MobileNet_V2' object has no attribute 'filter_tracked'
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

```

**Comment by leigh-johnson** [comment]
Thank you for catching and reporting this! 🙇‍♀️ 

Give this a whirl and let me know if this fixes the issue: `pip install --upgrade rpi-deep-pantilt==1.2.1`
