### ISSUE TITLE
 rpi-deep-pantilt not working (instantly crashing)

### ISSUE THREAD

**Issue by careyer** [leigh-johnson/rpi-deep-pantilt#61]
* rpi-deep-pantilt version: 1.2.1
* Python version: 3.7.3
* TensorFlow version: 2.4.0
* Operating System: RaspiOS lite (latest version)

### Description

Exactly followed along the install instructions (no errors during installation) but when running any command (test pantilt, test camera, detect...) then I get this error message:
```
(.venv) pi@raspberrypi:~ $ rpi-deep-pantilt test pantilt
Traceback (most recent call last):
  File "/home/pi/.venv/bin/rpi-deep-pantilt", line 5, in <module>
    from rpi_deep_pantilt.cli import main
  File "/home/pi/.venv/lib/python3.7/site-packages/rpi_deep_pantilt/cli.py", line 10, in <module>
    from rpi_deep_pantilt.detect.ssd_mobilenet_v3_coco import (
  File "/home/pi/.venv/lib/python3.7/site-packages/rpi_deep_pantilt/detect/ssd_mobilenet_v3_coco.py", line 9, in <module>
    from PIL import Image
  File "/home/pi/.venv/lib/python3.7/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
(.venv) pi@raspberrypi:~ $
```

### What I Did

I tried to run rpi-deep-pantilt without any command line parameters or with --help but it always crashes with the same error message as above.

Your help is much appreciated!
Thanks in advance!

Best regards
careyer

**Comment by careyer** [comment]
The following dependencies are missing:
`sudo apt install libtiff5  libopenjp2-7`
